sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t amaisenovich/docker-course .

script:
    - docker run -e CI=true amaisenovich/docker-course npm run test
